### ISSUE TITLE
Trash can't get recycled

### ISSUE THREAD

**Issue by Haano137** [viliger2/RoR2_Roomba#1]
![image](https://github.com/user-attachments/assets/dcd0b8d8-725b-4a3d-9495-0fc6bff24baa)

**Comment by viliger2** [comment]
It is intended behaviour so you can't get free yellows out of it. Game uses yellow items as key items, like artifact keys, for example that you also can't recycle or scrap.  I wanted to originally make it NoTier item but had issues with adding droplet to it, so instead it was made yellow.
